### PR TITLE
Add support for jsonb

### PR DESCRIPTION
**Pull request by lmivan**
New hibernate user type for Postgresql 9.4 jsonb.

### CODE REVIEW

**Comment by lmivan** [comment]
@Alotor If you like it you can try to publish a new version with our new credentials :-)

**Comment by Alotor** [comment]
Wow, you're amazing. I'll try to check it out tonight.

**Comment by Alotor** [comment]
We can try to publish tomorrow with the common credentials. Seems amazing how easy it's the code for this integration :smile:

**Comment by lmivan** [comment]
Please remember to update the version in the plugin descriptor file because I forgot it.

**Pull request merged**
