### PR TITLE
Ported to Grails 3.2 with support Hibernate 5.1.1.Final.

### PR DESCRIPTION
**Pull request by donbeave**
This is PR for https://github.com/kaleidos/grails-postgresql-extensions/issues/90 issue.

I also include this fix inside: https://github.com/kaleidos/grails-postgresql-extensions/pull/94.

### CODE REVIEW

**Comment by ilopmar** [comment]
Thank you very much! I really need to find time to review all pending MRs and merge this.

BTW, it seems that the tests are failing using JDK 7 because the class is compiled with JDK 8.

```
Execution failed for task ':compileGroovy'.
> org/postgresql/util/PGobject : Unsupported major.minor version 52.0
```

Any thoughts?

**Comment by donbeave** [comment]
Fixed.

**Comment by erichelgeson** [comment]
I'll be testing this tonight with the latest dbm snapshots and let you know how it goes. Great to see this updated!

**Comment by donbeave** [comment]
@erichelgeson @ilopmar guys, do you need any help? I can help you to review PR in this project. Our company @scentbird ([Scentbird](http://www.scentbird.com), it's a `perfume subscription service`) use this plugin in production. We have some resources to maintain this plugin, just in case, if you guys need some help.

**Comment by ilopmar** [comment]
I you guys confirm that the plugin is working, at least a can release a RC1 version even if I don't have time to merge it.

**Comment by erichelgeson** [comment]
I did some light testing and IMO it's worthy of an RC1. Mappings seem to work fine and works with the latest dbm snapshot:
```groovy
addColumn(tableName: "foo") {
    column(name: "data", type: "json") {
        constraints(nullable: "false")
    }
}
```
```
     Column     |            Type             | Modifiers 
----------------+-----------------------------+-----------
 id             | bigint                      | not null
 version        | bigint                      | not null
```

**Comment by ilopmar** [comment]
Excellent, I'll try to release a RC1 during the day or the weekend. I'll post it here once it's released.

Thank you for the help guys. I really appreciate it :)

**Comment by ilopmar** [comment]
Published

`compile 'org.grails.plugins:postgresql-extensions:5.0.0-RC1'`

Thank you again for your help!

**Comment by donbeave** [comment]
Thank you!

Btw, do you want to merge it into master or you want to separate into the single branch?

**Comment by ilopmar** [comment]
I'll merge it into `master` and I'll create a new branch for Hibernate 4. But before that I need to merge some other pending PRs and migrate all the documentation to Asciidoctor.

**Comment by donbeave** [comment]
@ilopmar I can help you with Asciidoctor.

**Comment by ilopmar** [comment]
My idea was to first refactor everything (that's why I migrated almost all Java code to Groovy + @CompileStatic) and then update the documentation using Asciidoctor extracting most of the code from the tests.

**Comment by erichelgeson** [comment]
Just ran into an issue on RC1 - We're seeing when using `dialect: net.kaleidos.hibernate.PostgresqlExtensionsDialect` and having `sequence_per_table` true (default) it is trying to use the default `hibernate_sequence` (sqllogging: `Hibernate: select nextval ('hibernate_sequence')`) - I'd expect it to use `select nextval('role_sequence')` as it did previously. 

If I do a `dbm-grom-diff` it wants to create the `hibernate_sequence` and drop the existing ones.

I can temporarily work around it with: 
`id generator: 'native', params: [sequence: 'seq_role']`

**Comment by ilopmar** [comment]
I've been debugging the issue and the method in the dialect is not executed. That's why there's only one sequence for all the tables. 
I'm trying to figure it out why it's not called and what I need to do to be executed. If you have some suggestions, please let me know.

**Comment by ilopmar** [comment]
@erichelgeson How are you adding the workaround, in the `mapping` block?

```
    static mapping = {
        id generator: 'native', params: [sequence: 'seq_role']
    }
```

This is not creating the sequence during the start up of the application.

**Comment by erichelgeson** [comment]
I removed the plugin, used default pg dialect, and used the mapping block yes. My migration already had the seq from my 3.1 app and this mapping allowed me to use them.

**Pull request closed without merging**
