### PR TITLE
Upgrade plugin to Grails 3

### PR DESCRIPTION
**Pull request by Poundex**
Squashed commit of the following:

commit dc904a50bf044e91997e6fa513e7cfd2b976776a
Author: Poundex <mail@poundex.net>
Date:   Wed Jul 22 21:20:34 2015 +0100

    Cleanup

commit 96c40a4513cbddf8d16d2d945091a0a48bbf738e
Author: Poundex <mail@poundex.net>
Date:   Wed Jul 22 19:55:09 2015 +0100

    Coverage (Cobertura + Coveralls)

commit 5998a86789b394dde3d3985b61137a4e3c33783d
Author: Poundex <mail@poundex.net>
Date:   Wed Jul 22 18:56:36 2015 +0100

    Upgrade to Grails 3

### CODE REVIEW

**Comment by lmivan** [comment]
Thank you very much for upgrading the plugin to Grails 3 :smiley: 

We're gonna take a look and try to publish in a couple of days.

Regards, Iván!

**Comment by lmivan** [comment]
I've done some cleaning, updating and published a SNAPSHOT version to bintray. It's not really a snapshot because it's not possible to do that in bintray, but if should be treated like that:

https://bintray.com/kaleidos/plugins/net.kaleidos%3Agrails-postgresql-extensions/5.0.0/

:warning: Please note tha the maven coordinates are not definitive. I need to talk with @Alotor about how are we going to maintain the different versions and their names. In the meantime you can use it just adding to your `gradle.build` file:

```
repositories {
    maven { url "http://dl.bintray.com/kaleidos/plugins" }
}

dependencies {
    compile 'net.kaleidos:postgresql-extensions:5.0.0'
}
```

**Comment by lmivan** [comment]
This PR is now merged! The `master` branch is now Grails 3 compliant! :smile: 

I've published to bintray the version 4.6.1 with the same functionality as the Grails 2 - Hibernate 4 branch.

**Comment by mengelhart** [comment]
Thanks for getting this out!   Having some trouble with gradle dependencies.. my build.gradle has the following:

repositories {
    mavenLocal()
    maven { url "https://repo.grails.org/grails/core" }
    maven { url "http://dl.bintray.com/kaleidos/plugins" }
}

and 
dependencies {
....
compile ":postgresql-extensions:4.6.1"
}

and I'm getting 
| Error Could not resolve all dependencies for configuration ':testRuntime'. Type 'gradle dependencies' for more information

Is there something else I need to be doing?

**Comment by lmivan** [comment]
I thought that once the plugin has been included in the grails 3 bintray plugins repository, it would be possible just to add the dependency and that's all. But it seems this is not true. I've asked about this in the Grails slack channel:
https://grails.slack.com/archives/plugins/p1443813532000165

In the mean time, as the plugin is also published in jcenter, you can do this:

```
repositories {
    ...
    // Just add jcenter
    jcenter()
    ...
}

dependencies {
    ...
    compile 'org.grails.plugins:postgresql-extensions:4.6.1'
    ...
}
```

I have tested deleting previously my maven-local downloaded copy and the plugin has been downloaded from jcenter.

I have created a new branch with the updated documentation for Grails 3 but it's not finished yet. I'll include the exact configuration.

**Comment by mengelhart** [comment]
Cool thanks so much lmivan.  that worked great.

**Comment by lmivan** [comment]
You're welcome. Thank you for the feedback :-)

**Pull request closed without merging**
