### PR TITLE
Exclude test files from plugin JAR

### PR DESCRIPTION
**Pull request by gregopet**
Patch both excludes classes from the generated JAR as well as from the `grails-plugin.xml` file.

### CODE REVIEW

**Comment by lmivan** [comment]
Thank you very much. I'll include this commit in the next release for Grails 3.X

**Comment by gregopet** [comment]
No problem - I have a User class in my project and it clashed with the one from the plugin so this was pretty high priority for me (I'm using a local fork of the plugin for the time being).

**Comment by lmivan** [comment]
Cherry-picked the changes and included now in the `master` branch.

Please check #70

**Comment by gregopet** [comment]
Did this patch make it into the published 5.0.0 version? I switched to it from my local fork and started getting `org.hibernate.DuplicateMappingException: duplicate import: User refers to both mypackage.User and test.criteria.array.User`

**Comment by lmivan** [comment]
I think I haven't been clear about this. I'm really sorry. 

The 5.0.0 version was something like a snapshot version. By that time we didn't know how we wanted to manage the different grails2, grails3, hibernate3 and hibernate4 versions. At the end, we decided to maintain the same version number for the grails2 and grails3 versions. That's why the released version is 4.6.1 because is the same as grails2.

The plugin is now included in the Grails 3 bintray repository (https://bintray.com/grails/plugins), so now I'm going to delete the 5.0.0 version. Please just use 4.6.1

Regards, Iván.

**Pull request closed without merging**
